export { default as IconExternal } from './external';
export { default as IconFolder } from './folder';
export { default as FormattedIcon } from './formattedIcon';
export { default as IconGitHub } from './github';
export { default as IconInstagram } from './instagram';
export { default as IconLinkedin } from './linkedin';
export { default as IconLocation } from './location';
export { default as IconLogo } from './logo';
export { default as IconFacebook } from './facebook';